import 'react';
import KemetAccordionClass from 'dist/kemet-accordion/kemet-accordion.d.mts';
import KemetAccordionPanelClass from 'dist/kemet-accordion/kemet-accordion-panel.d.mts';
import KemetAlertClass from 'dist/kemet-alert/kemet-alert.d.mts';
import KemetAvatarClass from 'dist/kemet-avatar/kemet-avatar.d.mts';
import KemetBadgeClass from 'dist/kemet-badge/kemet-badge.d.mts';
import KemetButtonClass from 'dist/kemet-button/kemet-button.d.mts';
import KemetCardClass from 'dist/kemet-card/kemet-card.d.mts';
import KemetCarouselClass from 'dist/kemet-carousel/kemet-carousel.d.mts';
import KemetCarouselCurrentClass from 'dist/kemet-carousel/kemet-carousel-current.d.mts';
import KemetCarouselFirstClass from 'dist/kemet-carousel/kemet-carousel-first.d.mts';
import KemetCarouselLastClass from 'dist/kemet-carousel/kemet-carousel-last.d.mts';
import KemetCarouselNextClass from 'dist/kemet-carousel/kemet-carousel-next.d.mts';
import KemetCarouselPrevClass from 'dist/kemet-carousel/kemet-carousel-prev.d.mts';
import KemetCarouselLinkClass from 'dist/kemet-carousel/kemet-carousel-link.d.mts';
import KemetCarouselSlideClass from 'dist/kemet-carousel/kemet-carousel-slide.d.mts';
import KemetCarouselTotalClass from 'dist/kemet-carousel/kemet-carousel-total.d.mts';
import KemetCheckboxClass from 'dist/kemet-checkbox/kemet-checkbox.d.mts';
import KemetComboClass from 'dist/kemet-combo/kemet-combo.d.mts';
import KemetCountClass from 'dist/kemet-count/kemet-count.d.mts';
import KemetDraggableClass from 'dist/kemet-draggable/kemet-draggable.d.mts';
import KemetDrawerClass from 'dist/kemet-drawer/kemet-drawer.d.mts';
import KemetFabClass from 'dist/kemet-fab/kemet-fab.d.mts';
import KemetFieldClass from 'dist/kemet-field/kemet-field.d.mts';
import KemetFlipcardClass from 'dist/kemet-flipcard/kemet-flipcard.d.mts';
import KemetFlipcardTriggerClass from 'dist/kemet-flipcard/kemet-flipcard-trigger.d.mts';
import KemetIconClass from 'dist/kemet-icon/kemet-icon.d.mts';
import KemetInputClass from 'dist/kemet-input/kemet-input.d.mts';
import KemetModalClass from 'dist/kemet-modal/kemet-modal.d.mts';
import KemetMultiInputClass from 'dist/kemet-multi-input/kemet-multi-input.d.mts';
import KemetPasswordClass from 'dist/kemet-password/kemet-password.d.mts';
import KemetPopperClass from 'dist/kemet-popper/kemet-popper.d.mts';
import KemetRadioClass from 'dist/kemet-radio/kemet-radio.d.mts';
import KemetRotatorClass from 'dist/kemet-rotator/kemet-rotator.d.mts';
import KemetSelectClass from 'dist/kemet-select/kemet-select.d.mts';
import KemetScrollNavClass from 'dist/kemet-scroll-nav/kemet-scroll-nav.d.mts';
import KemetScrollSnapClass from 'dist/kemet-scroll-snap/kemet-scroll-snap.d.mts';
import KemetScrollSnapPaginatorClass from 'dist/kemet-scroll-snap/kemet-scroll-snap-paginator.d.mts';
import KemetScrollSnapSlideClass from 'dist/kemet-scroll-snap/kemet-scroll-snap-slide.d.mts';
import KemetSortableClass from 'dist/kemet-sortable/kemet-sortable.d.mts';
import KemetSvgs from 'dist/kemet-svgs/kemet-svgs.d.mts';
import KemetTabClass from 'dist/kemet-tab/kemet-tab.d.mts';
import KemetTabPanelClass from 'dist/kemet-tab-panel/kemet-tab-panel.d.mts';
import KemetTabsClass from 'dist/kemet-tabs/kemet-tabs.d.mts';
import KemetTextareaClass from 'dist/kemet-textarea/kemet-textarea.d.mts';
import KemetTimerClass from 'dist/kemet-timer/kemet-timer.d.mts';
import KemetToggleClass from 'dist/kemet-toggle/kemet-toggle.d.mts';
import KemetTooltipClass from 'dist/kemet-tooltip/kemet-tooltip.d.mts';
import KemetTrackerClass from 'dist/kemet-tracker/kemet-tracker.d.mts';
import KemetUpload from 'dist/kemet-upload/kemet-upload.d.mts;'

declare module 'react' {
  namespace JSX {
    interface IntrinsicElements {
      'kemet-button': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetButtonClass;
      'kemet-accordion': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetAccordionClass;
      'kemet-accordion-panel': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetAccordionPanelClass;
      'kemet-alert': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetAlertClass;
      'kemet-avatar': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetAvatarClass;
      'kemet-badge': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetBadgeClass;
      'kemet-card': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetCardClass;
      'kemet-carousel': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetCarouselClass;
      'kemet-carousel-current': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetCarouselCurrentClass;
      'kemet-carousel-first': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetCarouselFirstClass;
      'kemet-carousel-last': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetCarouselLastClass;
      'kemet-carousel-next': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetCarouselNextClass;
      'kemet-carousel-prev': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetCarouselPrevClass;
      'kemet-carousel-link': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetCarouselLinkClass;
      'kemet-carousel-slide': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetCarouselSlideClass;
      'kemet-carousel-total': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetCarouselTotalClass;
      'kemet-checkbox': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetCheckboxClass;
      'kemet-combo': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetComboClass;
      'kemet-count': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetCountClass;
      'kemet-draggable': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetDraggableClass;
      'kemet-drawer': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetDrawerClass;
      'kemet-fab': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetFabClass;
      'kemet-field': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetFieldClass;
      'kemet-flipcard': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetFlipcardClass;
      'kemet-flipcard-trigger': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetFlipcardTriggerClass;
      'kemet-icon': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetIconClass;
      'kemet-input': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetInputClass;
      'kemet-modal': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetModalClass;
      'kemet-multi-input': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetMultiInputClass;
      'kemet-password': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetPasswordClass;
      'kemet-popper': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetPopperClass;
      'kemet-radio': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetRadioClass;
      'kemet-rotator': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetRotatorClass;
      'kemet-select': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetSelectClass;
      'kemet-scroll-nav': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetScrollNavClass;
      'kemet-scroll-snap': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetScrollSnapClass;
      'kemet-scroll-snap-paginator': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetScrollSnapPaginatorClass;
      'kemet-scroll-snap-slide': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetScrollSnapSlideClass;
      'kemet-sortable': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetSortableClass;
      'kemet-svgs': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetSvgs;
      'kemet-tab': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetTabClass;
      'kemet-tab-panel': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetTabPanelClass;
      'kemet-tabs': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetTabsClass;
      'kemet-textarea': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetTextareaClass;
      'kemet-timer': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetTimerClass;
      'kemet-toggle': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetToggleClass;
      'kemet-tooltip': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetTooltipClass;
      'kemet-tracker': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetTrackerClass;
      'kemet-upload': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & KemetUpload;
    }
  }
}
